language: python
python:
  - "2.6"
  - "2.7"
branches:
  only:
    - tutorial
install:
#  - pip install -r requirements.txt --use-mirrors
  - pip install pep8
script:
  - pep8 --exclude=migrations vespa
#  - ./vespa-core/vespa/starter.py
