language: python
python:
  - "2.6"
  - "2.7"
branches:
  only:
    - tutorial
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pep8
  - pip install coverage
  - pip install coveralls
script:
  - pep8 --exclude=migrations vespa
  - py.test
  - coverage report
#  - py.test --cov=vespa --cov-report=term
