language: python
python:
  - "2.6"
  - "2.7"
branches:
  only:
    - master
    - tutorial
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-libvirt
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pep8
  - pip install coverage
  - pip install coveralls
script:
  - pep8 --exclude=migrations vespa
  - coverage run --source=vespa setup.py test
#  - py.test --cov=vespa --cov-report=term
after_success:
  - coveralls
