language: python
python:
  - "2.7"
branches:
  only:
    - master
    - tutorial
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-libvirt libvirt-dev
  - cp /usr/lib/python2.7/dist-packages/libvirt* ~/virtualenv/python2.7/lib/python2.7/site-packages/
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pep8
  - pip install coverage
  - pip install coveralls
script:
  - pep8 --exclude=migrations vespa
  - coverage run --source=vespa setup.py test
#  - py.test --cov=vespa --cov-report=term
after_success:
  - coveralls
